default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: empathize_com_development

test:
  <<: *default
  database: empathize_com_test

production:
  <<: *default
  database: empathize_com_production
  username: empathize_com
  password: <%= ENV["EMPATHIZE_COM_DATABASE_PASSWORD"] %>
